DROP TABLE IF EXISTS URL;

CREATE TABLE URL(
  ID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  SHORT_URL VARCHAR(100),
  LONG_URL VARCHAR(200),
  CREATION_DATE TIMESTAMP,
  MODIFICATION_DATE TIMESTAMP,
  VERSION INT
);