DROP TABLE IF EXISTS URL;

CREATE TABLE URL(
  id INT IDENTITY PRIMARY KEY NOT NULL,
  shortUrl VARCHAR2(200),
  longUrl VARCHAR2(400),
  creationDate TIMESTAMP,
  modificationDate TIMESTAMP,
  version INT
);

